name: Atualizacao Automatica de Noticias

on:
  push:
    branches:
      - main
  schedule:
    # Atualiza automaticamente de 2 em 2 horas, todos os dias
    - cron: '0 */2 * * *'
  workflow_dispatch: # Botão manual ativo por segurança

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar o código do repositório
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Garante o histórico completo para evitar rejeições

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências se sobrarem
      run: |
        if [ -f package.json ]; then npm install; fi

    - name: Executar o script de notícias
      run: node processar_feeds.js

    - name: Guardar e enviar alterações para o GitHub
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        
        # 1. Fazemos o pull antes de adicionar o JSON para garantir sincronização limpa
        git pull origin main
        
        # 2. Adicionamos o novo ficheiro gerado pelo script
        git add noticias_final.json
        
        # 3. Fazemos o commit e o push limpo. Se não houver alterações, ele ignora sem dar erro
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Atualização automática de notícias [Skip CI]" && git push origin main)
